### ISSUE TITLE
Initial models?

### ISSUE THREAD

**Issue by ibadiu** [dipamgoswami/FeCAM#2]
Hi,
Thanks for sharing the code of your method!
We are running experiments with it and would like to run some reproducibility test.
Would it be possible to share the initial models used in the paper in order to facilitate these experiments?
Thank you!

**Comment by dipamgoswami** [comment]
Hi @ibadiu,

I have now shared the trained weights for the initial task used in our experiments. 
I added the link to the weights folder in the readme file.

Thanks!

**Comment by ibadiu** [comment]
Hi,
Thanks a lot for your prompt reply!
Would it be possible to also share the CIFAR weights?
Thanks!

**Comment by dipamgoswami** [comment]
Done.

**Comment by ibadiu** [comment]
Great, thanks!
