### ISSUE TITLE
question about backbone

### ISSUE THREAD

**Issue by yuzhang0403** [dipamgoswami/FeCAM#7]
Hello and thanks for your amazing work.
I noticed that in the paper it is mentioned that for both MSCIL and FSCIL settings, Resnet18 is used as the main network architecture, however in the code a pre-trained ViT model is used.
I would like to know whether the results in the FeCAM paper are based on ResNet18 or ViT.

**Comment by dipamgoswami** [comment]
Hi, the results in the FeCAM paper are based on both Resnet18 as well as pre-trained ViT. Most experiments in the paper for MSCIL and FSCIL are using Resnet18. We have the experiments using ViT models only in Table 2 of the paper. The network used for experiments is mentioned appropriately in the paper. Have a look.

So, we release the code for reproducing all these experiments.

**Comment by yuzhang0403** [comment]
Thank you for your response.
I misread the code regarding Table 1. I'm sorry for bothering you.
